logging:
  level:
    org.springframework.cloud.gateway: TRACE
    reactor.netty: TRACE
  endpoint:
    gateway:
      enabled: true
    health:
      group:
        custom:
          include:
            circuitBreakers
    web:
      exposure:
        include: "*"
server:
  error:
    include-binding-errors: always
    include-message: always

spring:
  cloud:
    gateway:
      httpserver:
        wiretap: true
      actuator:
        verbose:
          enabled: true
      routes:
        - id: test
          uri: "http://localhost"
          predicates:
            - Path=/bin/**
          filters:
            - StripPrefix=1
        - id: test-default
          uri: "http://localhost"
          predicates:
            - Path=/default/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 2
                redis-rate-limiter.requestedTokens: 1
        - id: test-wrapper
          uri: "http://localhost"
          predicates:
            - Path=/wrapper/**
          filters:
            - StripPrefix=1
            - RedisRequestRateLimiter
        - id: test-counters-route-1
          uri: "http://localhost"
          predicates:
            - Path=/counter/**
          filters:
            - StripPrefix=1
            - CountersRequestRateLimiter=1,30s
        - id: test-counters-route-2
          uri: "http://localhost"
          predicates:
            - Path=/counter2/**
          filters:
            - StripPrefix=1
            - CountersRequestRateLimiter=1,30s